    post:
         description: |
            新增优惠信息

            |参数 | 类型 | 描述 | 必选|
            |-------|------|------|------|
            |name|String| 活动名称| Yes|
            |type|String| 类型：money满减，rebate折扣| Yes|
            |rules|Array| 规则：例如：[{"full":100,"money":30},{"full":200,"money":50}]| No|
            |status|Int| 状态：1正常 0禁用 | No|
            |started_at|String| 开始时间 | Yes|
            |ended_at|String| 结束时间 | Yes|
         body:
            application/json:
                example: |
                   {
                      "shop_id":1,
                      "name":"新年满减活动188",
                      "type":"money",
                      "rules":[{
                          "full":100,
                          "money":30
                      },{
                          "full":200,
                          "money":50
                      }],
                      "status":1,
                      "started_at":"2018-2-20 12:00",
                      "ended_at":"2018-2-20 12:00",
                      "sort":1
                   }
         responses:
            201:
              description: "创建成功"
              body:
                  application/json:
                    example: |

            500:
              description: "请求失败"
              body:
                application/json:
                    example : !include ../examples/server_error.json

    get:
         description: |
            查询优惠列表

            |参数 | 类型 | 描述 | 必选|
            |-------|------|------|------|
            |page_size|String| 每页条数| No|
            |name|String| 优惠名称| No|
            |status|String| 状态| No|
            |type|String| 类型:rebate 折扣,money 满减,all 全部 | No|
            |node|String| 时间节点:notstart 未开始,starting 已开始,started 已结束| No|
            |started_at|String| 开始时间| No|
            |ended_at|String| 结束时间| No|
         responses:
            200:
              description: "请求成功"
              body:
                 application/json:
                       example: |
                          {
                              "current_page": 1,
                              "data": [
                                  {
                                      "id": 4,
                                      "name": "新年满减活动修改后",
                                      "status": 1,
                                      "type": "money",
                                      "rules": [
                                          {
                                              "full": 110,
                                              "money": 20
                                          },
                                          {
                                              "full": 210,
                                              "money": 30
                                          }
                                      ],
                                      "sort": 1,
                                      "started_at": "2018-01-20 12:00:00",
                                      "ended_at": "2018-02-20 12:00:00"
                                  },
                                  {
                                      "id": 6,
                                      "name": "新年满减活动6",
                                      "status": 1,
                                      "type": "money",
                                      "rules": [
                                          {
                                              "full": 100,
                                              "money": 30
                                          },
                                          {
                                              "full": 200,
                                              "money": 50
                                          }
                                      ],
                                      "sort": 1,
                                      "started_at": "2018-01-20 12:00:00",
                                      "ended_at": "2018-02-20 12:00:00"
                                  },
                                  {
                                      "id": 7,
                                      "name": "新年满减活动188",
                                      "status": 1,
                                      "type": "money",
                                      "rules": [
                                          {
                                              "full": 100,
                                              "money": 30
                                          },
                                          {
                                              "full": 200,
                                              "money": 50
                                          }
                                      ],
                                      "sort": 1,
                                      "started_at": "2018-01-20 12:00:00",
                                      "ended_at": "2018-02-20 12:00:00"
                                  }
                              ],
                              "first_page_url": "http://api.example.com/v1/promotions?page=1",
                              "from": 1,
                              "last_page": 1,
                              "last_page_url": "http://api.example.com/v1/promotions?page=1",
                              "next_page_url": null,
                              "path": "http://api.example.com/v1/promotions",
                              "per_page": 10,
                              "prev_page_url": null,
                              "to": 3,
                              "total": 3
                          }
            404:
              description: "请求失败"
              body:
                  application/json:
                       example: |
                          {
                             "errors": "资源不存在"
                          }

    /{promotion_id}:
          get:
                         description: |
                            优惠信息详情
                         responses:
                            200:
                              description: "请求成功"
                              body:
                                 application/json:
                                      example: |
                                         {
                                             "id": 4,
                                             "name": "新年满减活动修改后",
                                             "status": 1,
                                             "type": "money",
                                             "rules": [
                                                 {
                                                     "full": 110,
                                                     "money": 20
                                                 },
                                                 {
                                                     "full": 210,
                                                     "money": 30
                                                 }
                                             ],
                                             "sort": 1,
                                             "started_at": "2018-01-20 12:00:00",
                                             "ended_at": "2018-02-20 12:00:00"
                                         }
                            404:
                              description: "请求失败"
                              body:
                                application/json:
                                    example: |
                                       {
                                           "errors": "资源不存在"
                                       }
          put:
                                   description: |
                                      更新优惠信息

                                      |参数 | 类型 | 描述 | 必选|
                                      |-------|------|------|------|
                                      |name|String| 活动名称| Yes|
                                      |type|String| 类型：money满减，rebate折扣| Yes|
                                      |rules|Array| 规则：例如：[{"full":100,"money":30},{"full":200,"money":50}]| No|
                                      |status|Int| 状态：1正常 0禁用 | No|
                                      |started_at|String| 开始时间 | Yes|
                                      |ended_at|String| 结束时间 | Yes|
                                   body:
                                               application/json:
                                                   example: |
                                                      {
                                                      	"shop_id":1,
                                                      	"name":"新年满减活动修改后",
                                                      	"type":"money",
                                                      	"rules":[{
                                                      		"full":110,
                                                      		"money":20
                                                      	},{
                                                      		"full":210,
                                                      		"money":30
                                                      	}],
                                                      	"status":1,
                                                      	"started_at":"2018-1-20 12:00",
                                                      	"ended_at":"2018-2-20 12:00",
                                                      	"sort":1
                                                      }
                                   responses:
                                      200:
                                        description: "请求成功"
                                        body:
                                           application/json:
                                                example: |
                                                   {
                                                       "id": 4,
                                                       "name": "新年满减活动修改后",
                                                       "status": 1,
                                                       "type": "money",
                                                       "rules": [
                                                           {
                                                               "full": 110,
                                                               "money": 20
                                                           },
                                                           {
                                                               "full": 210,
                                                               "money": 30
                                                           }
                                                       ],
                                                       "sort": 1,
                                                       "started_at": "2018-1-20 12:00",
                                                       "ended_at": "2018-2-20 12:00"
                                                   }
                                      404:
                                        description: "请求失败"
                                        body:
                                          application/json:
                                              example: |
                                                 {
                                                     "errors": "资源不存在"
                                                 }
    delete:
         description: |
            删除优惠信息
         responses:
            204:
              description: "请求成功"
            404:
              description: "请求失败"
              body:
                application/json:
                    example: |
                       {
                           "errors": "Not found"
                       }